# Generated by Django 5.2.4 on 2025-09-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('monitoring', '0003_alter_customuser_managers_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'verbose_name': 'Sensor Data', 'verbose_name_plural': 'Sensor Data'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.permission'),
        ),
    ]
