# Generated by Django 5.2.4 on 2025-09-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_sensordata_options_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('sensor', 'Sensor Data'), ('alert', 'Alert'), ('system', 'System Log')], max_length=20)),
                ('content', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='STM32', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={},
        ),
    ]
